"""empty message

Revision ID: 83c14941cef0
Revises: 8c6ea24b3214
Create Date: 2023-10-16 15:49:01.087154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83c14941cef0'
down_revision = '8c6ea24b3214'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_quests_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('quest_id', sa.Integer(), nullable=True),
    sa.Column('last_given', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['quest_id'], ['quests_table.id'], name=op.f('fk_user_quests_table_quest_id_quests_table')),
    sa.ForeignKeyConstraint(['user_id'], ['users_table.id'], name=op.f('fk_user_quests_table_user_id_users_table')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('progress_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('progress_table',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('quest_id', sa.INTEGER(), nullable=True),
    sa.Column('last_given', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['quest_id'], ['quests_table.id'], name='fk_progress_table_quest_id_quests_table'),
    sa.ForeignKeyConstraint(['user_id'], ['users_table.id'], name='fk_progress_table_user_id_users_table'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_quests_table')
    # ### end Alembic commands ###
