"""new seed file

Revision ID: 8f7df7a33de9
Revises: 83c14941cef0
Create Date: 2023-10-18 10:18:27.824667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f7df7a33de9'
down_revision = '83c14941cef0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_table', schema=None) as batch_op:
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
